"""empty message

Revision ID: b8387ea80b99
Revises: ffdf4d7643bf
Create Date: 2018-05-02 09:31:50.750097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8387ea80b99'
down_revision = 'ffdf4d7643bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_books_btype'), 'books', ['btype'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_books_btype'), table_name='books')
    # ### end Alembic commands ###
